import { RouteInfo } from './sidebar.metadata';
const userInfo = JSON.parse(localStorage.getItem('currentUser'))
export const ROUTES: RouteInfo[] = [

  {
    path: '/admin/dashboard/main',
    title: 'Dashboard',
    moduleName: 'dashboard',
    iconType: 'material-icons-two-tone',
    icon: 'home',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin', 'Soldier'],
    submenu: [],
  },
  // {
  //   path: '',
  //   title: 'Profile',
  //   moduleName: 'profile',
  //   iconType: 'material-icons-two-tone',
  //   icon: 'person',
  //   class: 'menu-toggle',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   role: ['Soldier', 'Admin'],
  //   submenu: [
  //     {
  //       path: '/admin/profile/edit-profile',
  //       title: 'Edit Profile',
  //       moduleName: 'profile',
  //       iconType: '',
  //       icon: '',
  //       class: 'ml-menu',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       role: [''],
  //       submenu: [],
  //     },
  //   ],
  // },
  {
    path: '',
    title: 'Users',
    moduleName: 'users',
    iconType: 'material-icons-two-tone',
    icon: 'supervisor_account',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    submenu: [
      {
        path: '/admin/users/all-users',
        title: 'All Users',
        moduleName: 'users',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/admin/users/new-user',
        title: 'New User',
        moduleName: 'users',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/admin/users/user-requests',
        title: 'User Requests',
        moduleName: 'users',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'Imag Steganography',
    moduleName: 'image-steganography',
    iconType: 'material-icons-two-tone',
    icon: 'work',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    submenu: [
      {
        path: '/admin/stego/all-encrypted-image',
        title: 'All Embedde Data',
        moduleName: 'image-steganography',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/admin/stego/encrypt-image',
        title: 'Embed Image',
        moduleName: 'image-steganography',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },

    ],
  },
  {
    path: '',
    title: 'Inbox',
    moduleName: 'inbox',
    iconType: 'material-icons-two-tone',
    icon: 'email',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Soldier', 'Admin'],
    submenu: [
      {
        path: '/admin/inbox/all-messages',
        title: 'All Message',
        moduleName: 'inbox',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
    ],
  },

];
